[package]
name = "rustfst-ngram"
version = "0.1.0"
edition = "2021"
description = "Train N-Gram models as FSTs"
license = "BSD-2-Clause"

[dependencies]
anyhow = "1.0.68"
ordered-float = "3.4.0"
rustfst = "0.13.1"
